import type { DashboardProfile } from "../modules/types";

/** Pre-adaptive product-centric dashboard — used when no profile is stored. */
export const legacyDashboardProfile: DashboardProfile = {
  version: 1,
  source: "legacy",
  enabledModules: [
    "dashboard",
    "inbox",
    "products",
    "services",
    "catalogs",
    "orders",
    "customers",
    "agents",
    "knowledge",
    "workflows",
    "instagram",
    "settings",
  ],
  navigationItems: [
    "dashboard",
    "inbox",
    "products",
    "services",
    "catalogs",
    "orders",
    "customers",
    "agents",
    "knowledge",
    "workflows",
    "instagram",
    "settings",
  ],
  mobileNavigationItems: ["dashboard", "inbox", "products", "orders"],
  widgets: [
    {
      id: "conversations",
      label: "Biseda",
      hint: "Gjithsej në platformë",
      icon: "inbox",
      stat: "conversations",
    },
    {
      id: "orders",
      label: "Porosi të krijuara",
      hint: "Të gjitha statuset",
      icon: "orders",
      stat: "orders",
    },
    {
      id: "customers",
      label: "Klientë",
      hint: "Klientë të regjistruar",
      icon: "customers",
      tone: "blue",
      stat: "customers",
    },
    {
      id: "instagram",
      label: "Instagram i lidhur",
      hint: "Llogari me status të lidhur",
      icon: "instagram",
      tone: "pink",
      stat: "connections",
    },
  ],
  primaryActions: [
    {
      id: "add_product",
      label: "Shto produkte",
      href: "products",
      icon: "products",
    },
    {
      id: "view_orders",
      label: "Shiko porositë",
      href: "orders",
      icon: "orders",
    },
    {
      id: "update_knowledge",
      label: "Përditëso njohuritë",
      href: "knowledge",
      icon: "knowledge",
    },
    {
      id: "manage_instagram",
      label: "Menaxho Instagram",
      href: "instagram",
      icon: "instagram",
    },
  ],
};
