import type { ModuleDefinition, ModuleDependencyRule, ModuleId } from "./types";

export const moduleRegistry: Record<ModuleId, ModuleDefinition> = {
  dashboard: {
    id: "dashboard",
    path: "",
    label: "Dashboard",
    icon: "dashboard",
    core: true,
    mobilePriority: 1,
    description: "Përmbledhja e aktivitetit",
  },
  inbox: {
    id: "inbox",
    path: "inbox",
    label: "Inbox",
    icon: "inbox",
    core: true,
    mobilePriority: 2,
    description: "Bisedat me klientët",
  },
  products: {
    id: "products",
    path: "products",
    label: "Produkte",
    icon: "products",
    mobilePriority: 3,
    description: "Katalogu i produkteve",
  },
  services: {
    id: "services",
    path: "services",
    label: "Shërbime",
    icon: "knowledge",
    mobilePriority: 3,
    description: "Oferta e shërbimeve",
  },
  orders: {
    id: "orders",
    path: "orders",
    label: "Porosi",
    icon: "orders",
    mobilePriority: 4,
    description: "Porositë e klientëve",
  },
  bookings: {
    id: "bookings",
    path: "bookings",
    label: "Rezervime",
    icon: "orders",
    mobilePriority: 4,
    description: "Rezervimet dhe kërkesat",
  },
  calendar: {
    id: "calendar",
    path: "calendar",
    label: "Kalendari",
    icon: "calendar",
    description: "Orari dhe slotet",
  },
  staff: {
    id: "staff",
    path: "staff",
    label: "Stafi",
    icon: "businesses",
    description: "Anëtarët e ekipit",
  },
  catalogs: {
    id: "catalogs",
    path: "catalogs",
    label: "Katalogë",
    icon: "knowledge",
    mobilePriority: 3,
    description: "Katalogë B2B dhe dokumente",
  },
  leads: {
    id: "leads",
    path: "leads",
    label: "Leads",
    icon: "customers",
    mobilePriority: 4,
    description: "Kërkesa dhe lead-e",
  },
  customers: {
    id: "customers",
    path: "customers",
    label: "Klientë",
    icon: "customers",
    description: "Regjistri i klientëve",
  },
  agents: {
    id: "agents",
    path: "agents",
    label: "Agjenti AI",
    icon: "agents",
    core: true,
    description: "Konfigurimi i agjentit",
  },
  knowledge: {
    id: "knowledge",
    path: "knowledge",
    label: "Njohuria",
    icon: "knowledge",
    description: "FAQ, politika dhe njohuri",
  },
  workflows: {
    id: "workflows",
    path: "workflows",
    label: "Workflow",
    icon: "workflows",
    description: "Hapat e bisedës dhe porosive",
  },
  instagram: {
    id: "instagram",
    path: "instagram",
    label: "Instagram",
    icon: "instagram",
    core: true,
    description: "Lidhja me Instagram",
  },
  settings: {
    id: "settings",
    path: "settings",
    label: "Cilësimet",
    icon: "settings",
    core: true,
    description: "Cilësimet e hapësirës",
  },
};

/** Sidebar order when multiple modules are enabled. */
export const navigationOrder: ModuleId[] = [
  "dashboard",
  "inbox",
  "products",
  "services",
  "catalogs",
  "orders",
  "bookings",
  "calendar",
  "staff",
  "leads",
  "customers",
  "agents",
  "knowledge",
  "workflows",
  "instagram",
  "settings",
];

export const moduleDependencies: Record<ModuleId, ModuleDependencyRule> = {
  dashboard: { independent: true },
  inbox: { independent: true },
  products: { independent: true },
  services: { independent: true },
  orders: { requiresAny: ["products"] },
  bookings: { requires: ["services"] },
  calendar: { requiresAny: ["bookings"] },
  staff: { optionalFor: ["services", "bookings"] },
  catalogs: { independent: true },
  leads: { independent: true },
  customers: { independent: true },
  agents: { independent: true },
  knowledge: { independent: true },
  workflows: { independent: true },
  instagram: { independent: true },
  settings: { independent: true },
};

/** Modules admins can toggle in Settings → Modules. */
export const toggleableModules: ModuleId[] = [
  "products",
  "services",
  "orders",
  "bookings",
  "calendar",
  "staff",
  "catalogs",
  "leads",
  "customers",
  "knowledge",
  "workflows",
];
